"""This module contains several subclasses of ``QGraphicsScene``.
These are instantiated by `~astro3d.gui.astroVisual.MainPanel` and
are used to display the image and any regions.
Furthermore, `RegionStarScene` and `ClusterStarScene` allow
user input upon mouse click.

"""
from __future__ import division, print_function

# STDLIB
from collections import defaultdict

# Anaconda
from astropy.table import Table
from PyQt4.QtGui import *
from PyQt4.QtCore import *


class StarScene(QGraphicsScene):
    """This is a non-interactive subclass of ``QGraphicsScene``.
    It will display the image and any regions that have been added.

    Parameters
    ----------
    parent : `~astro3d.gui.astroVisual.MainPanel`
        The instantiating class.

    width, height : int
        The size of the `~astro3d.gui.astroVisual.MainPanel`,
        which allows `StarScene` to scale the image appropriately.

    Attributes
    ----------
    size : QSize
        Size of the `~astro3d.gui.astroVisual.MainPanel`.

    regions : dict
        Contains region type and a list of ``QGraphicsPolygonItem`` regions, which provides `StarScene` with a pointer to each region, allowing them to be removed if necessary. ``Region.name`` must contain region type.

    """
    _SCENE_COLOR = QColor(0, 100, 200)

    def __init__(self, parent, width, height):
        super(StarScene, self).__init__(parent)
        self.size = QSize(width, height)
        self.regions = defaultdict(list)

    def addImg(self, pixmap):
        """Scales the input pixmap to appropriate size for the
        `~astro3d.gui.astroVisual.MainPanel`, then adds it to
        the display. Adds all regions on top of image.

        .. note::

            Returns the scaled pixmap to save so that scaling will be
            unnecessary in the future.

        Parameters
        ----------
        pixmap : QPixmap

        Returns
        -------
        scaledPixmap : QPixmap

        """
        self.clear()
        scaledPixmap = pixmap.scaled(self.size, Qt.KeepAspectRatio)
        self.addItem(QGraphicsPixmapItem(scaledPixmap))
        for reglist in self.regions.itervalues():
            for reg in reglist:
                self.addItem(reg)
        return scaledPixmap

    def addReg(self, region):
        """Adds a given region to the display.

        .. note::

            The recursive behavior is for ``MergedRegion``,
            which is not currently supported.

        Parameters
        ----------
        region : `~astro3d.gui.astroObjects.Region`

        """
        if isinstance(region.region, (list, tuple)):
            return map(self.addReg, region.region)
        else:
            r = QGraphicsPolygonItem(region.region)
            r.setPen(self._SCENE_COLOR)
            self.addItem(r)
            self.regions[region.name].append(r)

    def delReg(self, region):
        """Remove a given region from the display.

        .. note::

            The recursive behavior is for ``MergedRegion``,
            which is not currently supported.

        Parameters
        ----------
        region : `~astro3d.gui.astroObjects.Region`

        """
        if isinstance(region.region, (list, tuple)):
            map(self.delReg, region.region)
        else:
            r = QGraphicsPolygonItem(region.region)
            self.removeItem(r)
            self.regions[region.name].remove(r)

    def clear(self):
        """Removes all items from the display without destroying
        instance variables.

        """
        for i in self.items():
            self.removeItem(i)


class RegionStarScene(QGraphicsScene):
    """This is an interactive subclass of ``QGraphicsScene``.
    Every time the user clicks on the image, it generates a point
    and adds it to a ``QPolygon``, allowing it to display that
    polygon as a region.

    Parameters
    ----------
    parent : `~astro3d.gui.astroVisual.MainPanel`
        The instantiating class.

    pixmap : QPixmap
        The scaled QPixmap generated by :meth:`StarScene.addImg`.
        It is added so that `RegionStarScene` can display the image.

    name : str
        Name (type) of the region to be drawn.

    Attributes
    ----------
    name : str
        Same as input.

    item : QGraphicsPixmapItem
        Created from ``pixmap``.

    points : list
        Points that have been added by the user.

    graphicspoints : list
        Displayed circles representing ``points``.

    shape : QPolygonF
        Polygon created from ``points``.

    display_shape : QGraphicsPolygonItem
        Display version of ``shape``.

    """
    _ELLIPSE_SZ = 10
    _ELLIPSE_RAD = _ELLIPSE_SZ // 2
    _ELLIPSE_COLOR = QColor(0, 255, 0)
    _REGION_COLOR = QColor(0, 100, 200)
    _MIN_POINTS = 3

    def __init__(self, parent, pixmap, name):
        super(RegionStarScene, self).__init__(parent)
        self.name = name
        self.item = QGraphicsPixmapItem(pixmap)
        self.addItem(self.item)
        self.points = []
        self.graphicspoints = []
        self.shape = None
        self.display_shape = None

    def mousePressEvent(self, event):
        """This method is called whenever the user clicks on
        `RegionStarScene`.

        It adds a new point clicked to ``points`` and ``graphicspoints``.
        If the point already exists, it is removed instead.
        If 3 or more points are added, it generates ``shape`` and
        ``display_shape`` to go along with it.

        Parameters
        ----------
        event : QEvent

        """
        p = event.scenePos()
        is_removed = False

        for i, gp in enumerate(self.graphicspoints):
            if gp.contains(p):
                is_removed = True
                self.removeItem(gp)
                self.graphicspoints.remove(gp)
                self.points.pop(i)
                break

        if not is_removed:
            e = QGraphicsEllipseItem(
                p.x() - self._ELLIPSE_RAD, p.y() - self._ELLIPSE_RAD,
                self._ELLIPSE_SZ, self._ELLIPSE_SZ)
            e.setPen(QPen(self._ELLIPSE_COLOR))
            self.addItem(e)
            self.graphicspoints.append(e)
            self.points.append(p)

        if self.display_shape is not None:
            self.removeItem(self.display_shape)

        if len(self.points) >= self._MIN_POINTS:
            self.shape = QPolygonF(self.points)
            self.display_shape = QGraphicsPolygonItem(self.shape)
            self.display_shape.setPen(QPen(self._REGION_COLOR))
            self.addItem(self.display_shape)
        else:
            self.shape = None
            self.displayshape = None

    def getRegion(self):
        """Returns the name (String) and shape (QPolygonF) of the region."""
        return self.name, self.shape

    def clear(self):
        """Removes all items from the display except the image.
        Resets all instance variables except for ``item``.

        """
        for i in self.items():
            self.removeItem(i)
        self.addItem(self.item)
        self.points = []
        self.graphicspoints = []
        self.shape = None
        self.display_shape = None


class RegionFileScene(QGraphicsScene):
    """Like `RegionStarScene` but the regions are pre-loaded from files."""
    _REGION_COLOR = QColor(0, 100, 200)

    def __init__(self, parent, pixmap, regions):
        super(RegionFileScene, self).__init__(parent)
        self.item = QGraphicsPixmapItem(pixmap)
        self.addItem(self.item)

        if isinstance(regions, list):
            self.name = [reg.name for reg in regions]
            self.shape = [reg.region for reg in regions]
            self.display_shape = []

            for s in self.shape:
                q = QGraphicsPolygonItem(s)
                q.setPen(QPen(self._REGION_COLOR))
                self.display_shape.append(q)
                self.addItem(q)

        else:
            self.name = regions.name
            self.shape = regions.region
            self.display_shape = QGraphicsPolygonItem(self.shape)
            self.addItem(self.display_shape)

    def getRegion(self):
        """Returns the name (string or list) and shapes (QPolygonF or list)
        of the regions.

        """
        return self.name, self.shape

    def clear(self):
        """Removes all items from the display except the image."""
        for i in self.items():
            self.removeItem(i)
        self.addItem(self.item)


class ClusterStarScene(QGraphicsScene):
    """An interactive subclass of ``QGraphicsScene``.
    Displays the given stars or star clusters, using circles
    to highlight their locations.

    The user may click on existing point to remove it from
    consideration, or on unmarked area to add it.

    Parameters
    ----------
    parent : `~astro3d.gui.astroVisual.MainPanel`
        The instantiating class.

    _file : `~astro3d.gui.astroObjects.File`
        File object.

    data : `astropy.table.Table`
        Table data to add.

    key : {'clusters', 'stars'}
        Type of ``File.peaks`` table to process.

    Attributes
    ----------
    _file, key
        Same as inputs.

    scale : float
        Scaling factor to convert between display and native coordinates.

    graphicspoints : QGraphicsEllipseItems
        Points displayed on screen.

    """
    _ELLIPSE_SZ = 10
    _ELLIPSE_RAD = _ELLIPSE_SZ // 2
    _ELLIPSE_COLOR = QColor(200, 50, 50)
    _FLUX_RAD = 5

    def __init__(self, parent, _file, data=None, key='clusters'):
        super(ClusterStarScene, self).__init__(parent)
        self._file = _file
        self.key = key
        self.scale = self._file.scale()
        self.graphicspoints = []

        # Display static background image
        self.addItem(QGraphicsPixmapItem(_file.image))

        if data is None:
            data = Table(names=['xcen', 'ycen', 'flux'])
        else:
            data.keep_columns(['xcen', 'ycen', 'flux'])
            xcen = data['xcen'] * self.scale
            ycen = data['ycen'] * self.scale
            for x, y in zip(xcen, ycen):
                self.add_point(x, y)

        self._file.peaks[self.key] = data

    def add_point(self, xcen, ycen):
        """Add a point to graphics scene.

        Parameters
        ----------
        xcen, ycen : float
            Coordinate of the point in display scale.

        """
        x = xcen - self._ELLIPSE_RAD
        y = ycen - self._ELLIPSE_RAD
        item = QGraphicsEllipseItem(x, y, self._ELLIPSE_SZ, self._ELLIPSE_SZ)
        item.setPen(QPen(self._ELLIPSE_COLOR))
        self.graphicspoints.append(item)
        self.addItem(item)

    def mousePressEvent(self, event):
        """This method is called whenever the user clicks
        on the screen.

        If the click is on one of the displayed
        points, that point is removed from the screen
        and table. Otherwise, it is added.

        Parameters
        ----------
        event : QEvent

        """
        p = event.scenePos()
        is_removed = False

        for i, gp in enumerate(self.graphicspoints):
            if gp.contains(p):
                is_removed = True
                self.removeItem(gp)
                self.graphicspoints.remove(gp)
                self._file.peaks[self.key].remove_row(i)
                break

        if not is_removed:
            xdisp = p.x()
            ydisp = p.y()
            xcen = xdisp / self.scale
            ycen = ydisp / self.scale

            # Estimate flux at selected point
            ix1 = max(int(xcen - self._FLUX_RAD), 0)
            ix2 = min(int(xcen + self._FLUX_RAD), self._file.data.shape[1])
            iy1 = max(int(ycen - self._FLUX_RAD), 0)
            iy2 = min(int(ycen + self._FLUX_RAD), self._file.data.shape[0])
            flux = self._file.data[iy1:iy2, ix1:ix2].sum()

            self.add_point(xdisp, ydisp)
            self._file.peaks[self.key].add_row([xcen, ycen, flux])
